### PR TITLE
Make setting jvmOptions a TaskKey

### PR DESCRIPTION
**Pull request by xbucchiotty**
This allow something like each run of the test to check for the environment and set some options to nodes

This enable something like starting a kafka server from sbt in a sbt docker, getting its dynamic port binding, and setting it to the nodes

kafkaStart in MultiJvm <<= Infra.Keys.kafkaStart runBefore (MultiJvmKeys.jvmOptions in MultiJvm)

kafkaStop in MultiJvm <<= Infra.Keys.kafkaStop triggeredBy (test in Test)

MultiJvmKeys.jvmOptions in MultiJvm := {
  Infra.Settings.kafkaPortMappings((baseDirectory in ThisProject).value / ".kafka").map {
    case (port, mapping) =>
      s"-Dkafka.$port=$mapping"
  }.toSeq ++ Seq(s"-Dkafka.host=${Infra.Keys.boot2docker_ip.value}")

### CODE REVIEW

**Comment by ktoso** [comment]
Smart change, thanks! LGTM

**Comment by ktoso** [comment]
Hi @xbucchiotty,
Thanks again for your contribution. Before we can merge this you'll need to sign our Contributor Agreement, you just have to have a short read and confirm you agree to it here: http://www.typesafe.com/contribute/cla (confirming online using your github account is enough)

Thanks in advance!

**Comment by xbucchiotty** [comment]
Done

Thanks to you for this awesome test framework!

The testConductor with throttling and blackhole is really useful for our
use-cases, µservice with akka-cluster

2015-01-08 18:19 GMT+01:00 Konrad Malawski <notifications@github.com>:

> Hi @xbucchiotty <https://github.com/xbucchiotty>,
> Thanks again for your contribution. Before we can merge this you'll need
> to sign our Contributor Agreement, you just have to have a short read and
> confirm you agree to it here: http://www.typesafe.com/contribute/cla
> (confirming online using your github account is enough)
>
> Thanks in advance!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/typesafehub/sbt-multi-jvm/pull/23#issuecomment-69213899>
> .
>



-- 

Xavier Bucchiotty

[image: Xebia logo] <http://www.xebia.fr/>
« Software Development Done Right »
156, boulevard Haussmann, 75008 Paris
xbucchiotty@xebia.fr[image: Great Place To Work 2014]
<http://www.greatplacetowork.fr/>

[image: Alliance logo]

**Comment by xbucchiotty** [comment]
Agreements confirmed




Le 8 janv. 2015 à 18:19, Konrad Malawski <notifications@github.com> a
écrit :

Hi @xbucchiotty <https://github.com/xbucchiotty>,
Thanks again for your contribution. Before we can merge this you'll need to
sign our Contributor Agreement, you just have to have a short read and
confirm you agree to it here: http://www.typesafe.com/contribute/cla
(confirming online using your github account is enough)

Thanks in advance!

—
Reply to this email directly or view it on GitHub
<https://github.com/typesafehub/sbt-multi-jvm/pull/23#issuecomment-69213899>
.

**Comment by ktoso** [comment]
Thanks a lot @xbucchiotty :-)

**Pull request merged**
