### PR TITLE
updates for sbt 0.13.7

### PR DESCRIPTION
**Pull request by msfrank**
* bump sbt-assembly dependency to 0.12.0

### CODE REVIEW

**Comment by ktoso** [comment]
Hi @msfrank,
Thanks a lot for your contribution! I'll need to go over it on my machine, but seems to look OK from the outside.

Before we can merge this you'll need to sign our Contributor Agreement, you just have to have a short read and confirm you agree to it here: http://www.typesafe.com/contribute/cla (confirming online using your github account is enough)

Thanks in advance!

**Comment by ktoso** [comment]
I have verified this update works with the akka build (on master, since there we're on sbt 0.13.x).
Once the CLA is signed this seems LGTM to me.

**Comment by bantonsson** [comment]
Thanks for testing @ktoso 

The code LGTM. Thanks again @msfrank for the contribution.

**Comment by msfrank** [comment]
cool!  its enough for me to just acknowledge in this PR that i accept the CLA?  if so, then yes, i acknowledge and accept the individual CLA referenced here: http://www.typesafe.com/contribute/cla

**Comment by bantonsson** [comment]
@msfrank you need to confirm it with your GitHub account here http://www.typesafe.com/contribute/cla/verify as described in Step 2 on the http://www.typesafe.com/contribute/cla page.

**Comment by msfrank** [comment]
@bantonsson done.

**Comment by ktoso** [comment]
Confirmed and merged, thanks a lot for the contribution @msfrank! :-)

**Pull request merged**
